service:
  name: reimagine-processors

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::reimagine.io-warehouse/*"

custom:
  myVpc:
    securityGroupIds:
      - sg-a95b0cdd
    subnetIds:
      - subnet-24c0a40b
      - subnet-134ad24e
      - subnet-73351838

functions:
  segmentGetter:
    handler: src/get-segment/get-segment.handler
    vpc: ${self:custom.myVpc}
  midiPoster:
    handler: src/post-midi/post-midi.handler
    vpc: ${self:custom.myVpc}
  recordingPoster:
    handler: src/post-recording/post-recording.handler
    vpc: ${self:custom.myVpc}
