service:
  name: reimagine

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  midiSegmentizer:
    handler: handler.segmentize
    events:
      - http:
          method: post
          path: newMidi
    vpc:
      securityGroupIds:
        - sg-a95b0cdd
      subnetIds:
        - subnet-24c0a40b
        - subnet-134ad24e
        - subnet-73351838
